### ISSUE TITLE
Pull Request?

### ISSUE THREAD

**Issue by pschorf** [mla/text-forge#2]
Hi:

As part of the CPAN pull request challenge, I'd like to help contribute to text-forge. I was wondering if there was anything in particular you thought needed attention or if I should just dive in.

Thank you,
Paul

**Comment by mla** [comment]
Hi, Paul. Cool!

There's a couple of things that have been asked for. I just added issue #3 which is to allow the user to change the start/end tag characters of the template blocks.

Also, currently the tests are generated with a customized version of Test::Inline, which is hard for anyone else other than me to generate. We need to decide whether we want to strip the tests out into normal TAP tests or improve the inline test stuff so it's more accessible.

Open to other ideas though. Let's me know if you have any questions or problems with the code.

**Comment by pschorf** [comment]
Great, thanks! I'll get started with that this week.
